### ISSUE TITLE
Error after restarting the machine

### ISSUE THREAD

**Issue by elliot710** [Ph3nol/Trading-Bot#1]
In Filesystem.php line 59:

 Failed to copy "/app/scripts/ui-instance-entrypoint.sh" to "/tmp/manager/scripts/ui-instance-entrypoint.sh" because target file could not be opened for writing.

status [<instance>]

**Comment by Ph3nol** [comment]
Hey!
First of all, thank you for you feedback! You're awesome!
A big update will be pushed tonight (in a few hour here in France 😉 ) and should fix this point!
Installation becomes super-easy with this update and a demo config will be given too.
Stay tuned! 🤓
