### ISSUE TITLE
The script is exposing the UI to 0.0.0.0:80 but it's not available to host

### ISSUE THREAD

**Issue by elliot710** [Ph3nol/Trading-Bot#2]
Calling curl http://container_ip:80 is working but curl localhost:80 is returning error:
 Failed to connect to localhost port 80: Connection refused. I think it should work since in Dockerfile port is binded to host

**Comment by elliot710** [comment]
Thank you! You made a great job! Looking forward to try it

**Comment by Ph3nol** [comment]
In fact, 2 solutions :
- 1 UI for multiple Instances (but 1 Session, so logout to check another instance is required)
- 1 UI for 1 instance (so 1 port by UI instance), allows us to have multiple UI/Instances simultaneously (chosen solution for this Trading Bot)
![image](https://user-images.githubusercontent.com/183984/110634659-832b2b80-81aa-11eb-96e7-3dffcb68b822.png)

Each UI is available from `bot status`. Just click on "UI"! 😉

**Comment by elliot710** [comment]
> In fact, 2 solutions :
> 
>     * 1 UI for multiple Instances (but 1 Session, so logout to check another instance is required)
> 
>     * 1 UI for 1 instance (so 1 port by UI instance), allows us to have multiple UI/Instances simultaneously (chosen solution for this Trading Bot)
>       ![image](https://user-images.githubusercontent.com/183984/110634659-832b2b80-81aa-11eb-96e7-3dffcb68b822.png)
> 
> 
> Each UI is available from `bot status`. Just click on "UI"! 😉

Click on what, I'm in terminal, no desktop environment.

**Comment by Ph3nol** [comment]
![image](https://user-images.githubusercontent.com/183984/110643513-74497680-81b4-11eb-84e3-faf42c073fe9.png)

Click on this! It's a link, from Terminal.

**Comment by elliot710** [comment]
Ha ha, that's what I thought but it's not clickable to me :D

There is not a configuration setting, or something?

**Comment by Ph3nol** [comment]
Oh! Sorry about that! Hum... You can get your generated UI port from `_instances/<your_instance_slug>/parameters.json`
![image](https://user-images.githubusercontent.com/183984/110661563-fcd01300-81c4-11eb-8696-288ead12f3ff.png)

**Comment by Ph3nol** [comment]
Many things has been updated since our last messages. I close this issue in favour of possible new ones to create.
