### ISSUE TITLE
Como actualizar configuraciones

### ISSUE THREAD

**Issue by martip07** [Ph3nol/Trading-Bot#4]
Hola,

Quiero actualizar configuraciones en una instancia que cree para BUSD.

Lo que quiero actualizar es el usuario y contraseña para el UI - API pero al ejecutar esto en instancias de pruebas me sale un mensaje que toda la data previamente guardada se va a perder. Y no quiero que esto pase ya que llevo ejecutando el bot un par de días.

Gracias.

**Comment by Ph3nol** [comment]
Hey,

When you say that you are using the bot for some days, you talk about my Trading Bot or an independant Freqtrade instance?

PS: please prefer english for communicating here.

**Comment by martip07** [comment]
Sure, from now on only English.

Yep, I am talking about your bot.

**Comment by Ph3nol** [comment]
OK! Perfect!

There were many improvements and update these past few days.

This Trading Bot is in BETA version and I'm sorry about that.

If you want to "backup" you DB, be sure about saving your `_instances/.../db/*` files. Just to be sure.
![image](https://user-images.githubusercontent.com/183984/110957564-01730380-834c-11eb-9417-4cb6cd5e271a.png)

Then you can update your version, with making a new install of the bot.

Finally, run a `bot status` from you config directory to see if everything is OK.

Waiting for your feedback about this update. Thank you.

**Comment by martip07** [comment]
Sure, before continue. Just some questions:

1. Blacklist is for symbols that the bot won't use for trading, right?
2. Whitelist or Blacklist must be configured with like this,  ["ETHUSDT", "BTCUSDT"] or [ETHUSDT, BTCUSDT]?

Regards,

**Comment by Ph3nol** [comment]
This Trading Bot is a manager for [Freqtrade](https://github.com/freqtrade/freqtrade/), which is the engine.

If you want more informations about the trading configuration, take an eye to its [documentation](https://www.freqtrade.io/en/latest/).

The Freqtrade configuration has to be present as `config.json` file into the Trading Bot configs directory, and will be used for your instance(s).
You can take a look at the [Demo Config](https://github.com/Ph3nol/Trading-Bot-Config).

I hope all these information will help you. Be strong! 💪

**Comment by Ph3nol** [comment]
This Trading Bot is a manager for [Freqtrade](https://github.com/freqtrade/freqtrade/), which is the engine.

If you want more informations about the trading configuration, take an eye to its [documentation](https://www.freqtrade.io/en/latest/).

The Freqtrade configuration has to be present as `config.json` file into the Trading Bot configs directory, and will be used for your instance(s).
You can take a look at the [Demo Config](https://github.com/Ph3nol/Trading-Bot-Config).

I hope all these informations will help you. Be strong! 💪
