### ISSUE TITLE
Auth failure with Binance

### ISSUE THREAD

**Issue by forcespikejan** [Ph3nol/Trading-Bot#5]
First of all I want to say good job for the manager, it looks great.

So I installed the bot on a fresh Digitalocean Docker Droplet. I set up two strategies and dryrun went nicely. I decided to go live with them but when I put in API key and secret, I get binance {"code":-2014,"msg":"API-key format invalid." message from Binance.

It is unclear to me why Binance woud specifically report apikey FORMAT when only key/secret would be wrong

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 75, in __init__
    self.wallets = Wallets(self.config, self.exchange)
  File "/freqtrade/freqtrade/wallets.py", line 35, in __init__
    self.update()
  File "/freqtrade/freqtrade/wallets.py", line 117, in update
    self._update_live()
  File "/freqtrade/freqtrade/wallets.py", line 91, in _update_live
    balances = self._exchange.get_balances()
  File "/freqtrade/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 148, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/freqtrade/freqtrade/exchange/common.py", line 151, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 689, in get_balances
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: binance {"code":-2014,"msg":"API-key format invalid."}
```

**Comment by Ph3nol** [comment]
It seems the problem is more with your Freqtrade config (from .json or .yaml file).
Where is your token filled in? YAML file [like here](https://github.com/Ph3nol/Trading-Bot-Config/blob/master/manager.yaml#L18) ?
Your can surround it with `"` like this:

```
parameters:
    ...

instances:
  _all:
    config:
      ...
      exchange:
        key: "xxx"
        secret: "xxx"
...
```

What about this?

**Comment by forcespikejan** [comment]
My config in strategy.json is 

```
  "exchange": {
    "name": "binance",
    "key": "xxx",
    "secret": "xxx",
    "ccxt_config": {"enableRateLimit": true},
    "ccxt_async_config": {
        "enableRateLimit": true,
        "rateLimit": 200
    },
```

I tried to follow your advice and put key+secret directly to YAML but it is the same result.

strategy.json
```
  "exchange": {
    "name": "binance",
    "ccxt_config": {"enableRateLimit": true},
    "ccxt_async_config": {
        "enableRateLimit": true,
        "rateLimit": 200
    },
```


manager.yaml
```
instances: 
 _all:
    config:
      exchange:
        key: "xxx"
        secret: "xxx"
```

 Strangely this is done from the template config, i must be doing some stupid mistake, but I honestly cannot find it.

**Comment by Ph3nol** [comment]
Hum, is `bot status` OK?
If it is, please check how looks your `_instances/<your-instance-name>/config.ready.json`. It should contain your exchange key and token, ready for being used by Freqtrade.

**Comment by forcespikejan** [comment]
`bot status` is ok for few seconds then Core turns X

The correct keys are in the `config.ready.json`
```
    "exchange": {
        "name": "binance",
        "key": "xxx",
        "secret": "xxx",
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [],
        "pair_blacklist": []
    },
```

**Comment by forcespikejan** [comment]
So I created a new Droplet of the bot

I did not touch anything in the config files except the keys and `dry_run`
[instance.log](https://github.com/Ph3nol/Trading-Bot/files/6148108/instance.log)
[config1.zip](https://github.com/Ph3nol/Trading-Bot/files/6148146/config1.zip)

**Comment by Ph3nol** [comment]
OH!!! EUREKA!

It's not a problem with Freqtrade or this Trading Bot, the problem is returned by Binance API itself... (code -2014). And I presume "your API-key format is invalid"! 😅

Please check it (or try to regenerate it from Binance). I am pretty sure the problem is there!

**Comment by forcespikejan** [comment]
Oh crap, I feel so stupid now. There was a typo when I was copying the key and then I did not re-check it with binance every time :)

**Comment by Ph3nol** [comment]
It can happen! No problem!
Enjoy now! 🚀
